language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
install:
  - pip install -r requirements.txt pylint
script:
  - python -m unittest
  - pylint --rcfile=pylint.rc osctiny