language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
install:
  - pip install -r requirements.txt pylint
script:
  - python -m unittest
  - pylint --rcfile=pylint.rc osctiny
deploy:
  provider: pypi
  skip_existing: true
  skip_cleanup: true
  user: crazyphd
  password:
    secure: "Lj6v5u2HbvphhCna7svb2xJy52+u9nJ3RjoSsuQCisaJFxUOY4hvyvdvfBXG7ou8gD5JLHBhNPmqUqHBEKo0Ze1RCET9lSQSMZ0CnXVwCgv4zPpqKlG3xmW+k49ohXfoEOd+B836/VUQN8Lu813+vcacG31OLBhdIUNLpmPSlKBSLJQJXa/7/wUPvtbozmuyIElgvmYtgqacHTMf6+fqhHlFGPqostB5i4jL2vmbKGb7z+UXf8Io54zkejQwJbgiXOVzVmzNWFu8LAAjZ2J+kBb25+lTDUd7/kgYiUEK2eiedYB7kdte2SdwIgG9pCUezqCDzP6AB+zqjvCYvUYLZ9eKK059+n4uzZSoDPSTjzzwNMkYSZoYfSEe+SphjZXJYTuZSXqdWSSIliHJPe0Zu6ny1OWr/C1lgZ6F5IfcIHV+bRZ7ERGta5hDiFGGcvkkC+zTdMdhygN3fv4Ep1gEymqGxypblcMH3bIWHeo/6zbqtNkcYpjSrb9zl9Y8BplktUJK4vqNAvlm8MCWmYv1iqO7Gmz8/nmPPO0tEtFZ8DoghNvGbYtZg8Kc9+HcC1342+Ly+5rhslUeg8b3tYs00LsNuK484mUoAyLRDKBvgWsgEdd9roMS6srUifilGXYKqr00IXoe2aMw9D5TFbnPa6p+1LW/H1YWpsvnn11mfik="
  on:
    tags: true
    branch: master